--- #YAML:1.0
name:               File-RelDir
version:            0.1
abstract:           This module provides a mechanism to determine the relative path between two directory names.
author:
    - Dave Roberts (droberts@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
